package com.nengliang.web.entity;

import java.io.Serializable;

public class HouseXiao implements Serializable{


	private static final long serialVersionUID = -890529210423885669L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_house_xiao.xid
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    private Long xid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_house_xiao.xname
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    private String xname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_house_xiao.id
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_house_xiao.xid
     *
     * @return the value of com_house_xiao.xid
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    public Long getXid() {
        return xid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_house_xiao.xid
     *
     * @param xid the value for com_house_xiao.xid
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    public void setXid(Long xid) {
        this.xid = xid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_house_xiao.xname
     *
     * @return the value of com_house_xiao.xname
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    public String getXname() {
        return xname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_house_xiao.xname
     *
     * @param xname the value for com_house_xiao.xname
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    public void setXname(String xname) {
        this.xname = xname == null ? null : xname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_house_xiao.id
     *
     * @return the value of com_house_xiao.id
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_house_xiao.id
     *
     * @param id the value for com_house_xiao.id
     *
     * @mbggenerated Tue Feb 25 11:27:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }
}