package com.nengliang.web.dao;

import com.github.pagehelper.PageRowBounds;
import com.nengliang.web.entity.HouseXiao;
import com.nengliang.web.entity.HouseXiaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseXiaoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int countByExample(HouseXiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int deleteByExample(HouseXiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int deleteByPrimaryKey(Long xid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int insert(HouseXiao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int insertSelective(HouseXiao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	List<HouseXiao> selectByExample(HouseXiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	HouseXiao selectByPrimaryKey(Long xid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int updateByExampleSelective(@Param("record") HouseXiao record, @Param("example") HouseXiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int updateByExample(@Param("record") HouseXiao record, @Param("example") HouseXiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int updateByPrimaryKeySelective(HouseXiao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table com_house_xiao
	 *
	 * @mbggenerated Tue Feb 25 11:27:27 CST 2020
	 */
	int updateByPrimaryKey(HouseXiao record);

	List<HouseXiao> selectPage(@Param("page") Integer page, @Param("size") Integer size);

}